kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-volume1
    labels:
      type: local
  spec:
    storageClassName: manual
    capacity:
      storage: 1Mi
    persistentVolumeReclaimPolicy: Recycle
    accessModes: 
      - ReadWriteOnce
    hostPath:
      path: "/mnt/wsl/docker-desktop/data/data1"
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-volume2
    labels:
      type: local
  spec:
    storageClassName: manual
    capacity:
      storage: 1Mi
    persistentVolumeReclaimPolicy: Recycle
    accessModes: 
      - ReadWriteOnce
    hostPath:
      path: "/mnt/wsl/docker-desktop/data/data2"
