apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node 
  serviceName: node
  replicas: 2
  template:
    metadata:
      labels:
        app: node
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: node
        image: luksa/kubia-pet
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /var/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests: 
          storage: 1Mi
      storageClassName: manual
