apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
spec:
  replicas: 2
  selector:
    app: web-server
  template:
   metadata:
     labels:
       app: web-server
   spec:
     containers:
     - name: web
       image: nginx
       ports:
       - containerPort: 8080
